In [3]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd
import seaborn as sns

In [4]:
all_datsets = sns.get_dataset_names()

In [6]:
all_datsets

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
#anagrams dataset

In [7]:
df_anagrams = sns.load_dataset('anagrams')

what is the anagrams                                                                                                    

*It's a small toy/example dataset bundled with Seaborn for teaching/plotting.
It contains words (or word-like strings) where some rows are anagrams of others.
The dataset also includes a couple of numeric example columns (you already saw num1 and num2) that are synthetic/features for plotting or demonstration, not intrinsic to the anagram relation.*

In [8]:
df_anagrams

,subidr,attnr,num1,num2,num3
0,1,divided,2,4.0,7
1,2,divided,3,4.0,5
2,3,divided,3,5.0,6
3,4,divided,5,7.0,5
4,5,divided,4,5.0,8
5,6,divided,5,5.0,6
6,7,divided,5,4.5,6
7,8,divided,5,7.0,8
8,9,divided,2,3.0,7
9,10,divided,6,5.0,6


In [9]:
df_anagrams.head(4)

,subidr,attnr,num1,num2,num3
0,1,divided,2,4.0,7
1,2,divided,3,4.0,5
2,3,divided,3,5.0,6
3,4,divided,5,7.0,5


In [10]:
df_anagrams.tail(6)

,subidr,attnr,num1,num2,num3
14,15,focused,8,8.0,7
15,16,focused,6,8.0,7
16,17,focused,7,7.0,6
17,18,focused,7,8.0,6
18,19,focused,5,6.0,6
19,20,focused,6,6.0,5


In [12]:
df_anagrams.shape

(20, 5)

In [15]:
df_anagrams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   subidr  20 non-null     int64  
 1   attnr   20 non-null     object 
 2   num1    20 non-null     int64  
 3   num2    20 non-null     float64
 4   num3    20 non-null     int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 932.0+ bytes


In [16]:
df_anagrams.describe()

,subidr,num1,num2,num3
count,20.00000,20.000000,20.00000,20.000000
mean,10.50000,5.350000,5.97500,6.550000
std,5.91608,1.843195,1.67391,1.099043
min,1.00000,2.000000,3.00000,5.000000
25%,5.75000,4.750000,5.00000,6.000000
50%,10.50000,5.500000,5.50000,6.000000
75%,15.25000,6.250000,7.25000,7.000000
max,20.00000,8.000000,9.00000,9.000000


In [27]:
df_anagrams.describe()

,subidr,num1,num2,num3,num4
count,20.00000,20.000000,20.00000,20.000000,20.000000
mean,10.50000,5.350000,5.97500,6.550000,5.350000
std,5.91608,1.843195,1.67391,1.099043,1.843195
min,1.00000,2.000000,3.00000,5.000000,2.000000
25%,5.75000,4.750000,5.00000,6.000000,4.750000
50%,10.50000,5.500000,5.50000,6.000000,5.500000
75%,15.25000,6.250000,7.25000,7.000000,6.250000
max,20.00000,8.000000,9.00000,9.000000,8.000000


In [18]:
df_anagrams.describe(include='all')

,subidr,attnr,num1,num2,num3
count,20.00000,20,20.000000,20.00000,20.000000
unique,NaN,2,NaN,NaN,NaN
top,NaN,divided,NaN,NaN,NaN
freq,NaN,10,NaN,NaN,NaN
mean,10.50000,NaN,5.350000,5.97500,6.550000
std,5.91608,NaN,1.843195,1.67391,1.099043
min,1.00000,NaN,2.000000,3.00000,5.000000
25%,5.75000,NaN,4.750000,5.00000,6.000000
50%,10.50000,NaN,5.500000,5.50000,6.000000
75%,15.25000,NaN,6.250000,7.25000,7.000000


In [19]:
df_anagrams['num1'].unique()

array([2, 3, 5, 4, 6, 8, 7])

In [20]:
df_anagrams['num2'].unique()

array([4. , 5. , 7. , 4.5, 3. , 9. , 8. , 6. ])

In [21]:
df_anagrams['num1'].nunique()

7

In [24]:
df_anagrams['num4'] = df_anagrams['num1'].astype(int)

In [25]:
df_anagrams['num4']

0     2
1     3
2     3
3     5
4     4
5     5
6     5
7     5
8     2
9     6
10    6
11    8
12    6
13    8
14    8
15    6
16    7
17    7
18    5
19    6
Name: num4, dtype: int64

In [26]:
df_anagrams['num4'].nunique()

7

In [28]:
df_anagrams.isnull().sum()

subidr    0
attnr     0
num1      0
num2      0
num3      0
num4      0
dtype: int64

In [ ]:
#anscombe dataset

*It's Seaborn's copy of Anscombe's quartet (a classic example from statistics).
Purpose: show that datasets with identical summary statistics (mean, variance, correlation, regression line) can have very different distributions and visual patterns — so you must plot your data, not only rely on summary numbers.*

In [29]:
df_anscombe = sns.load_dataset('anscombe')

In [32]:
df_anscombe.head(5)

,dataset,x,y
0,I,10.0,8.04
1,I,8.0,6.95
2,I,13.0,7.58
3,I,9.0,8.81
4,I,11.0,8.33


In [33]:
df_anscombe.tail(5)

,dataset,x,y
39,IV,8.0,5.25
40,IV,19.0,12.50
41,IV,8.0,5.56
42,IV,8.0,7.91
43,IV,8.0,6.89


In [34]:
df_anscombe.describe()


,x,y
count,44.000000,44.000000
mean,9.000000,7.500682
std,3.198837,1.958925
min,4.000000,3.100000
25%,7.000000,6.117500
50%,8.000000,7.520000
75%,11.000000,8.747500
max,19.000000,12.740000


In [35]:
df_anscombe.describe(include='all')


,dataset,x,y
count,44,44.000000,44.000000
unique,4,NaN,NaN
top,I,NaN,NaN
freq,11,NaN,NaN
mean,NaN,9.000000,7.500682
std,NaN,3.198837,1.958925
min,NaN,4.000000,3.100000
25%,NaN,7.000000,6.117500
50%,NaN,8.000000,7.520000
75%,NaN,11.000000,8.747500


In [37]:
df_anscombe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   dataset  44 non-null     object 
 1   x        44 non-null     float64
 2   y        44 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.2+ KB


In [39]:
df_anscombe['x'].unique()

array([10.,  8., 13.,  9., 11., 14.,  6.,  4., 12.,  7.,  5., 19.])

In [40]:
df_anscombe['y'].unique()

array([ 8.04,  6.95,  7.58,  8.81,  8.33,  9.96,  7.24,  4.26, 10.84,
        4.82,  5.68,  9.14,  8.14,  8.74,  8.77,  9.26,  8.1 ,  6.13,
        3.1 ,  9.13,  7.26,  4.74,  7.46,  6.77, 12.74,  7.11,  7.81,
        8.84,  6.08,  5.39,  8.15,  6.42,  5.73,  6.58,  5.76,  7.71,
        8.47,  7.04,  5.25, 12.5 ,  5.56,  7.91,  6.89])

In [42]:
df_anscombe['x'].nunique()

12

In [43]:
df_anscombe['y'].nunique()

43

In [44]:
df_anscombe.isnull()

,dataset,x,y
0,False,False,False
1,False,False,False
2,False,False,False
3,False,False,False
4,False,False,False
5,False,False,False
6,False,False,False
7,False,False,False
8,False,False,False
9,False,False,False


In [45]:
df_anscombe.isnull().sum()

dataset    0
x          0
y          0
dtype: int64

In [47]:
df_anscombe['z']=df_anscombe['x'].astype(int)

In [51]:
df_anscombe['z'].unique()

array([10,  8, 13,  9, 11, 14,  6,  4, 12,  7,  5, 19])

In [ ]:
#attention dataset

It's a small example/tutor dataset bundled with Seaborn for demonstrating plotting of time-series / repeated-measure data and grouping/faceting.
It usually contains measurements of attention (or a proxy) across multiple time points/conditions and subjects/trials so you can practice line plots, error bands, and faceting.

In [52]:
df_attention = sns.load_dataset('attention')

In [53]:
df_attention.head(5)

,Unnamed: 0,subject,attention,solutions,score
0,0,1,divided,1,2.0
1,1,2,divided,1,3.0
2,2,3,divided,1,3.0
3,3,4,divided,1,5.0
4,4,5,divided,1,4.0


In [54]:
df_attention.tail(5)

,Unnamed: 0,subject,attention,solutions,score
55,55,16,focused,3,7.0
56,56,17,focused,3,6.0
57,57,18,focused,3,6.0
58,58,19,focused,3,6.0
59,59,20,focused,3,5.0


In [55]:
df_attention.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  60 non-null     int64  
 1   subject     60 non-null     int64  
 2   attention   60 non-null     object 
 3   solutions   60 non-null     int64  
 4   score       60 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 2.5+ KB


In [56]:
df_attention.describe()

,Unnamed: 0,subject,solutions,score
count,60.000000,60.000000,60.000000,60.000000
mean,29.500000,10.500000,2.000000,5.958333
std,17.464249,5.814943,0.823387,1.621601
min,0.000000,1.000000,1.000000,2.000000
25%,14.750000,5.750000,1.000000,5.000000
50%,29.500000,10.500000,2.000000,6.000000
75%,44.250000,15.250000,3.000000,7.000000
max,59.000000,20.000000,3.000000,9.000000


In [57]:
df_attention.describe(include='all')

,Unnamed: 0,subject,attention,solutions,score
count,60.000000,60.000000,60,60.000000,60.000000
unique,NaN,NaN,2,NaN,NaN
top,NaN,NaN,divided,NaN,NaN
freq,NaN,NaN,30,NaN,NaN
mean,29.500000,10.500000,NaN,2.000000,5.958333
std,17.464249,5.814943,NaN,0.823387,1.621601
min,0.000000,1.000000,NaN,1.000000,2.000000
25%,14.750000,5.750000,NaN,1.000000,5.000000
50%,29.500000,10.500000,NaN,2.000000,6.000000
75%,44.250000,15.250000,NaN,3.000000,7.000000


In [59]:
df_attention.isnull().sum()

Unnamed: 0    0
subject       0
attention     0
solutions     0
score         0
dtype: int64

In [60]:
df_attention['subject'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
df_attention['subject'].nunique()

20

In [62]:
df_attention['attention'].unique()

array(['divided', 'focused'], dtype=object)

In [63]:
df_attention['attention'].nunique()

2

In [65]:
df_attention['newcol'] = df_attention['subject'].astype(int)

In [66]:
df_attention['newcol'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
df_attention['newcol'].nunique()

20

#brain_networks data type

It's a small example dataset bundled with Seaborn for demonstrating network/graph-style data and connectivity visualizations.
Conceptually it's an edge-list or connection table: each row usually describes a link between two brain regions (nodes) with a numeric strength/weight and possibly metadata such as subject, condition, frequency band, or ROI labels.
Typical use cases: make adjacency matrices, compute network measures, or plot connections between regions.

In [68]:
df_brain_networks = sns.load_dataset('brain_networks')


In [69]:
df_brain_networks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 63 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   network  922 non-null    object
 1   1        922 non-null    object
 2   1.1      922 non-null    object
 3   2        922 non-null    object
 4   2.1      922 non-null    object
 5   3        922 non-null    object
 6   3.1      922 non-null    object
 7   4        922 non-null    object
 8   4.1      922 non-null    object
 9   5        922 non-null    object
 10  5.1      922 non-null    object
 11  6        922 non-null    object
 12  6.1      922 non-null    object
 13  6.2      922 non-null    object
 14  6.3      922 non-null    object
 15  7        922 non-null    object
 16  7.1      922 non-null    object
 17  7.2      922 non-null    object
 18  7.3      922 non-null    object
 19  7.4      922 non-null    object
 20  7.5      922 non-null    object
 21  8        922 non-null    object
 22  8.

In [70]:
df_brain_networks.head(5)


,network,1,1.1,2,2.1,3,3.1,4,4.1,5,...,16.5,16.6,16.7,17,17.1,17.2,17.3,17.4,17.5,17.6
0,node,1,1,1,1,1,1,1,1,1,...,3,4,4,1,1,2,2,3,3,4
1,hemi,lh,rh,lh,rh,lh,rh,lh,rh,lh,...,rh,lh,rh,lh,rh,lh,rh,lh,rh,lh
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,56.05574417114258,92.03103637695312,3.391575574874878,38.65968322753906,26.203819274902344,-49.71556854248047,47.4610366821289,26.746612548828125,-35.898860931396484,...,0.6079040169715881,-70.27054595947266,77.36577606201172,-21.73455047607422,1.0282527208328247,7.7917842864990225,68.90372467041016,-10.520872116088867,120.49046325683594,-39.686431884765625
4,1,55.5472526550293,43.6900749206543,-65.49598693847656,-13.974522590637207,-28.27496337890625,-39.05012893676758,-1.2106596231460571,-19.012897491455078,19.568010330200195,...,57.49507141113281,-76.39321899414062,127.26136016845705,-13.035799026489258,46.3818244934082,-15.752449989318848,31.00033187866211,-39.607521057128906,24.76401138305664,-36.7710075378418


In [71]:
df_brain_networks.tail(5)

,network,1,1.1,2,2.1,3,3.1,4,4.1,5,...,16.5,16.6,16.7,17,17.1,17.2,17.3,17.4,17.5,17.6
918,915,-7.4295125007629395,-4.81321907043457,-3.670536518096924,1.4422610998153689,-19.6804313659668,-29.109355926513672,-3.3765623569488525,-8.764892578125,0.017911728471517563,...,58.28579330444336,68.55741119384766,22.83304786682129,76.17948913574219,51.9346694946289,-6.614512920379639,-6.690762042999268,22.893030166625977,48.27437973022461,76.22845458984375
919,916,-33.55413818359375,-38.60562133789063,-25.66480255126953,-30.252351760864254,5.5627851486206055,20.182186126708984,17.91124725341797,24.65358161926269,-32.93561172485352,...,59.86481857299805,23.00457763671875,7.6574625968933105,50.96239852905274,13.696922302246096,63.50361633300781,57.40117645263672,24.97454833984375,51.97215270996094,64.53878784179689
920,917,-78.53956604003906,-74.19718933105469,-54.04159545898438,-39.97029113769531,-14.277058601379395,-30.606460571289066,60.62852096557617,62.02702331542969,-32.80055618286133,...,68.76786804199219,49.66401672363281,64.55149841308594,43.80074691772461,8.144479751586914,47.28145980834961,70.49964904785156,66.99440002441406,81.53924560546875,64.96977233886719
921,918,-103.23582458496094,-98.7442855834961,-40.10954284667969,-44.90773391723633,12.109148025512695,1.6213401556015017,33.765560150146484,55.35607147216797,-14.330512046813965,...,103.1552505493164,106.45484924316406,9.04682731628418,46.67441940307617,40.95479583740234,0.8771800398826599,37.57715225219727,20.517745971679688,3.124434232711792,56.71838760375977
922,919,-36.28886795043945,-10.762069702148438,-30.35626220703125,-23.31950378417969,14.252187728881836,-27.55986022949219,17.279512405395508,-19.060152053833008,26.55877685546875,...,102.0863037109375,80.05113983154297,-2.6426103115081787,-12.229619979858398,-6.596726417541504,17.665163040161133,16.153173446655273,8.300398826599121,33.687530517578125,17.960655212402344


In [72]:
df_brain_networks.isnull().sum()

network    1
1          1
1.1        1
2          1
2.1        1
          ..
17.2       1
17.3       1
17.4       1
17.5       1
17.6       1
Length: 63, dtype: int64

In [73]:
df_brain_networks.describe()


,network,1,1.1,2,2.1,3,3.1,4,4.1,5,...,16.5,16.6,16.7,17,17.1,17.2,17.3,17.4,17.5,17.6
count,922,922,922,922,922,922,922,922,922,922,...,922,922,922,922,922,922,922,922,922,922
unique,922,922,922,922,922,922,922,922,922,922,...,922,922,922,922,922,922,922,922,922,922
top,node,1,1,1,1,1,1,1,1,1,...,3,4,4,1,1,2,2,3,3,4
freq,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1


In [74]:
df_brain_networks.describe(include='all')
    

,network,1,1.1,2,2.1,3,3.1,4,4.1,5,...,16.5,16.6,16.7,17,17.1,17.2,17.3,17.4,17.5,17.6
count,922,922,922,922,922,922,922,922,922,922,...,922,922,922,922,922,922,922,922,922,922
unique,922,922,922,922,922,922,922,922,922,922,...,922,922,922,922,922,922,922,922,922,922
top,node,1,1,1,1,1,1,1,1,1,...,3,4,4,1,1,2,2,3,3,4
freq,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1


In [77]:
df_brain_networks['1.1'].unique()

array(['1', 'rh', nan, '92.03103637695312', '43.6900749206543',
       '63.43879318237305', '12.65715789794922', '-63.10466766357422',
       '-51.19189453125', '0.5400829315185547', '10.650232315063477',
       '46.36944961547852', '33.998897552490234', '-15.77474880218506',
       '-74.31371307373047', '-18.707275390625', '-38.97297286987305',
       '-47.51335906982422', '-13.10137939453125', '17.155952453613278',
       '-18.9571475982666', '11.07896327972412', '4.405511856079102',
       '35.86621856689453', '24.615583419799805', '-15.824548721313475',
       '-31.08311462402344', '-47.32866668701172', '-36.231346130371094',
       '-32.697513580322266', '-22.471235275268555', '-7.137496471405028',
       '-27.222278594970703', '-73.34848022460938', '-38.09075927734375',
       '-54.77230072021485', '1.5351393222808838', '8.959338188171387',
       '56.81584167480469', '11.506900787353516', '-41.44362258911133',
       '-9.615896224975586', '-63.96927261352539', '-65.9427108764648

In [78]:
df_brain_networks['1.1'].nunique()

922

In [80]:
df_brain_networks['1.1'].isnull().sum()

np.int64(1)

In [79]:
df_brain_networks['new'] = df_brain_networks['1.1'].astype(int)

ValueError: invalid literal for int() with base 10: 'rh'

#it give the error because already there is an signle  null value as in previous cell output 

In [ ]:
#car_crashes data set

car_crashes is a small example dataset bundled with Seaborn for demonstration and plotting. It contains per-state measures related to car crashes and risk factors (numeric features) and a state abbreviation column. It’s a teaching dataset — use it to practice scatterplots, correlation/heatmaps, bar charts, and simple aggregations.

In [81]:
df_car_crashes = sns.load_dataset('car_crashes')

In [82]:
df_car_crashes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   total           51 non-null     float64
 1   speeding        51 non-null     float64
 2   alcohol         51 non-null     float64
 3   not_distracted  51 non-null     float64
 4   no_previous     51 non-null     float64
 5   ins_premium     51 non-null     float64
 6   ins_losses      51 non-null     float64
 7   abbrev          51 non-null     object 
dtypes: float64(7), object(1)
memory usage: 3.3+ KB


In [83]:
df_car_crashes.describe()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,15.790196,4.998196,4.886784,13.573176,14.004882,886.957647,134.493137
std,4.122002,2.017747,1.729133,4.508977,3.764672,178.296285,24.835922
min,5.900000,1.792000,1.593000,1.760000,5.900000,641.960000,82.750000
25%,12.750000,3.766500,3.894000,10.478000,11.348000,768.430000,114.645000
50%,15.600000,4.608000,4.554000,13.857000,13.775000,858.970000,136.050000
75%,18.500000,6.439000,5.604000,16.140000,16.755000,1007.945000,151.870000
max,23.900000,9.450000,10.038000,23.661000,21.280000,1301.520000,194.780000


In [84]:
df_car_crashes.describe(include='all')

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AL
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
mean,15.790196,4.998196,4.886784,13.573176,14.004882,886.957647,134.493137,NaN
std,4.122002,2.017747,1.729133,4.508977,3.764672,178.296285,24.835922,NaN
min,5.900000,1.792000,1.593000,1.760000,5.900000,641.960000,82.750000,NaN
25%,12.750000,3.766500,3.894000,10.478000,11.348000,768.430000,114.645000,NaN
50%,15.600000,4.608000,4.554000,13.857000,13.775000,858.970000,136.050000,NaN
75%,18.500000,6.439000,5.604000,16.140000,16.755000,1007.945000,151.870000,NaN


In [85]:
df_car_crashes.head(5)

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA


In [86]:
df_car_crashes.tail(5)

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY


In [87]:
df_car_crashes.isnull().sum()

total             0
speeding          0
alcohol           0
not_distracted    0
no_previous       0
ins_premium       0
ins_losses        0
abbrev            0
dtype: int64

In [88]:
df_car_crashes['total'].unique()

array([18.8, 18.1, 18.6, 22.4, 12. , 13.6, 10.8, 16.2,  5.9, 17.9, 15.6,
       17.5, 15.3, 12.8, 14.5, 15.7, 17.8, 21.4, 20.5, 15.1, 12.5,  8.2,
       14.1,  9.6, 17.6, 16.1, 14.9, 14.7, 11.6, 11.2, 18.4, 12.3, 16.8,
       23.9, 19.9, 18.2, 11.1, 19.4, 19.5, 11.3, 12.7, 10.6, 23.8, 13.8,
       17.4])

In [89]:
df_car_crashes['total'].nunique()

45

In [90]:
df_car_crashes['newtotal'] = df_car_crashes['total'].astype(int)

In [91]:
df_car_crashes['newtotal'].unique()

array([18, 22, 12, 13, 10, 16,  5, 17, 15, 14, 21, 20,  8,  9, 11, 23, 19])

In [92]:
df_car_crashes['newtotal'].nunique()

17

diamonds dataset

A medium-size example dataset (from ggplot2/diamonds) used to demonstrate regression, categorical plots, and multivariate exploration. Each row is a single diamond with physical measurements and price.


In [93]:
df_diamonds=sns.load_dataset('diamonds')

In [98]:
df_diamonds.head(5)

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


In [99]:
df_diamonds.tail(5)

,carat,cut,color,clarity,depth,table,price,x,y,z
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64


In [94]:
df_diamonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   carat    53940 non-null  float64 
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64 
 5   table    53940 non-null  float64 
 6   price    53940 non-null  int64   
 7   x        53940 non-null  float64 
 8   y        53940 non-null  float64 
 9   z        53940 non-null  float64 
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB


In [95]:
df_diamonds.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000


In [96]:
df_diamonds.describe(include='all')

,carat,cut,color,clarity,depth,table,price,x,y,z
count,53940.000000,53940,53940,53940,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
unique,NaN,5,7,8,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Ideal,G,SI1,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,21551,11292,13065,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.797940,NaN,NaN,NaN,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,NaN,NaN,NaN,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,NaN,NaN,NaN,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,NaN,NaN,NaN,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,NaN,NaN,NaN,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,NaN,NaN,NaN,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000


In [100]:
df_diamonds.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [101]:
df_diamonds['carat'].unique()

array([0.23, 0.21, 0.29, 0.31, 0.24, 0.26, 0.22, 0.3 , 0.2 , 0.32, 0.33,
       0.25, 0.35, 0.42, 0.28, 0.38, 0.7 , 0.86, 0.71, 0.78, 0.96, 0.73,
       0.8 , 0.75, 0.74, 0.81, 0.59, 0.9 , 0.91, 0.61, 0.77, 0.63, 0.76,
       0.64, 0.72, 0.79, 0.58, 1.17, 0.6 , 0.83, 0.54, 0.98, 0.52, 1.01,
       0.53, 0.84, 0.51, 1.05, 0.55, 0.87, 1.  , 0.57, 0.82, 1.04, 0.93,
       1.2 , 0.99, 0.34, 0.43, 0.36, 0.95, 0.89, 1.02, 0.97, 0.56, 0.85,
       0.92, 1.27, 0.66, 1.12, 0.68, 1.03, 0.62, 1.22, 1.08, 0.88, 0.5 ,
       1.19, 0.39, 0.65, 1.24, 1.5 , 0.27, 0.41, 1.13, 1.06, 0.69, 0.4 ,
       1.14, 0.94, 1.29, 1.52, 1.16, 1.21, 1.23, 1.09, 0.67, 1.11, 1.1 ,
       1.18, 1.15, 1.25, 1.07, 1.28, 1.51, 0.37, 1.31, 1.26, 1.39, 1.44,
       1.35, 1.3 , 1.32, 1.41, 1.36, 1.45, 1.34, 1.58, 1.54, 1.38, 1.33,
       1.74, 1.64, 1.47, 1.4 , 1.55, 1.95, 2.  , 1.37, 1.83, 1.62, 1.57,
       1.69, 2.06, 1.72, 1.66, 2.14, 1.49, 1.46, 2.15, 1.96, 2.22, 1.7 ,
       1.53, 1.85, 2.01, 2.27, 1.68, 1.56, 1.81, 1.

In [102]:
df_diamonds['carat'].nunique()

273

In [103]:
df_diamonds['new_carat'] = df_diamonds['carat'].astype(int)


In [104]:
df_diamonds['new_carat'].unique()

array([0, 1, 2, 3, 4, 5])

In [105]:
df_diamonds['new_carat'].nunique()

6

dots dataset

A small toy dataset Seaborn provides to demonstrate dot/point categorical plots and within-subject (repeated measures) displays.
Expect one numeric measurement column and one or more categorical columns (condition/factor, maybe subject id or time). Column names vary by Seaborn version — inspect first to see exact names.


In [106]:
df_dots = sns.load_dataset('dots')


In [107]:
df_dots.head(5)

,align,choice,time,coherence,firing_rate
0,dots,T1,-80,0.0,33.189967
1,dots,T1,-80,3.2,31.691726
2,dots,T1,-80,6.4,34.279840
3,dots,T1,-80,12.8,32.631874
4,dots,T1,-80,25.6,35.060487


In [108]:
df_dots.tail(5)

,align,choice,time,coherence,firing_rate
843,sacc,T2,300,3.2,33.281734
844,sacc,T2,300,6.4,27.583979
845,sacc,T2,300,12.8,28.511530
846,sacc,T2,300,25.6,27.009804
847,sacc,T2,300,51.2,30.959302


In [109]:
df_dots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848 entries, 0 to 847
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   align        848 non-null    object 
 1   choice       848 non-null    object 
 2   time         848 non-null    int64  
 3   coherence    848 non-null    float64
 4   firing_rate  848 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 33.3+ KB


In [110]:
df_dots.describe()

,time,coherence,firing_rate
count,848.000000,848.000000,848.000000
mean,74.150943,12.898113,39.616662
std,284.596669,15.453506,12.232967
min,-600.000000,0.000000,6.275720
25%,-100.000000,3.200000,32.620191
50%,80.000000,6.400000,38.022005
75%,260.000000,12.800000,47.383649
max,720.000000,51.200000,70.048900


In [111]:
df_dots.describe(include='all')

,align,choice,time,coherence,firing_rate
count,848,848,848.000000,848.000000,848.000000
unique,2,2,NaN,NaN,NaN
top,sacc,T2,NaN,NaN,NaN
freq,454,430,NaN,NaN,NaN
mean,NaN,NaN,74.150943,12.898113,39.616662
std,NaN,NaN,284.596669,15.453506,12.232967
min,NaN,NaN,-600.000000,0.000000,6.275720
25%,NaN,NaN,-100.000000,3.200000,32.620191
50%,NaN,NaN,80.000000,6.400000,38.022005
75%,NaN,NaN,260.000000,12.800000,47.383649


In [112]:
df_dots.isnull().sum()

align          0
choice         0
time           0
coherence      0
firing_rate    0
dtype: int64

In [113]:
df_dots['align'].isnull().sum()

np.int64(0)

In [117]:
df_dots['align'].unique()

array(['dots', 'sacc'], dtype=object)

In [118]:
df_dots['time'].unique()

array([ -80,  -60,  -40,  -20,    0,   20,   40,   60,   80,  100,  120,
        140,  160,  180,  200,  220,  240,  260,  280,  300,  320,  340,
        360,  380,  400,  420,  440,  460,  480,  500,  520,  540,  560,
        580,  600,  620,  640,  660,  680,  700,  720, -600, -580, -560,
       -540, -520, -500, -480, -460, -440, -420, -400, -380, -360, -340,
       -320, -300, -280, -260, -240, -220, -200, -180, -160, -140, -120,
       -100])

In [119]:
df_dots['time'].nunique()

67

dowjones dataset

A  small time-series dataset of Dow Jones stock/market data used for plotting examples.
Expect a date column plus price-related columns (common names: date, open, high, low, close, volume, maybe adj_close or price). Exact names vary by version — inspect to be sure.


In [120]:
df_dowjones = sns.load_dataset("dowjones")

In [121]:
df_dowjones.head(5)

,Date,Price
0,1914-12-01,55.00
1,1915-01-01,56.55
2,1915-02-01,56.00
3,1915-03-01,58.30
4,1915-04-01,66.45


In [122]:
df_dowjones.tail(5)

,Date,Price
644,1968-08-01,883.72
645,1968-09-01,922.80
646,1968-10-01,955.47
647,1968-11-01,964.12
648,1968-12-01,965.39


In [123]:
df_dowjones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    649 non-null    datetime64[ns]
 1   Price   649 non-null    float64       
dtypes: datetime64[ns](1), float64(1)
memory usage: 10.3 KB


In [124]:
df_dowjones.describe()

,Date,Price
count,649,649.000000
mean,1941-11-30 17:42:48.258859776,290.807319
min,1914-12-01 00:00:00,46.850000
25%,1928-06-01 00:00:00,106.900000
50%,1941-12-01 00:00:00,172.270000
75%,1955-06-01 00:00:00,436.730000
max,1968-12-01 00:00:00,985.930000
std,NaN,256.062906


In [125]:
df_dowjones.describe(include='all')

,Date,Price
count,649,649.000000
mean,1941-11-30 17:42:48.258859776,290.807319
min,1914-12-01 00:00:00,46.850000
25%,1928-06-01 00:00:00,106.900000
50%,1941-12-01 00:00:00,172.270000
75%,1955-06-01 00:00:00,436.730000
max,1968-12-01 00:00:00,985.930000
std,NaN,256.062906


In [126]:
df_dowjones.isnull().sum()

Date     0
Price    0
dtype: int64

In [127]:
df_dowjones['Price'].isnull().sum()

np.int64(0)

In [129]:
df_dowjones['Price'].unique()

array([ 55.  ,  56.55,  56.  ,  58.3 ,  66.45,  65.95,  68.4 ,  71.85,
        79.25,  85.5 ,  92.35,  94.35,  97.  ,  94.7 ,  93.55,  93.3 ,
        89.75,  90.15,  90.65,  88.45,  91.  ,  97.45, 102.1 , 107.9 ,
        98.5 ,  97.15,  90.95,  94.65,  93.9 ,  93.35,  96.95,  92.9 ,
        88.65,  83.6 ,  79.05,  71.4 ,  70.2 ,  76.6 ,  79.95,  78.05,
        77.65,  81.05,  80.45,  81.85,  81.95,  82.5 ,  86.25,  84.  ,
        81.65,  82.45,  86.55,  91.15,  99.4 , 103.6 , 109.7 , 103.25,
       108.2 , 113.9 , 111.6 , 105.8 , 105.9 ,  96.5 ,  97.95,  99.45,
        91.1 ,  91.7 ,  90.7 ,  85.25,  86.5 ,  84.85,  79.3 ,  72.2 ,
        74.75,  75.7 ,  75.05,  77.  ,  76.7 ,  69.2 ,  68.6 ,  66.95,
        69.35,  71.7 ,  79.8 ,  80.6 ,  83.75,  87.2 ,  91.3 ,  93.95,
        95.  ,  99.2 ,  99.75,  95.75,  98.2 , 100.8 , 103.9 , 100.55,
        95.5 ,  92.55,  89.3 ,  90.45,  90.75,  88.15,  94.1 ,  97.8 ,
        98.8 ,  95.6 ,  91.95,  90.4 ,  99.25, 103.55, 102.9 , 101.65,
      

In [130]:
df_dowjones['Price'].nunique()

637

Exercise Dataset

exercise is a small teaching dataset packaged with Seaborn for demonstrating repeated-measures / simple experimental data and plotting.
It usually records a measured response (e.g., pulse/heart-rate or calories) across time/conditions for subjects, with one or more categorical factors (diet/kind/time). Exact column names can vary by Seaborn/version, so confirm with an inspect.

In [131]:
df_exercise = sns.load_dataset('exercise')

In [132]:
df_exercise.head(5)

,Unnamed: 0,id,diet,pulse,time,kind
0,0,1,low fat,85,1 min,rest
1,1,1,low fat,85,15 min,rest
2,2,1,low fat,88,30 min,rest
3,3,2,low fat,90,1 min,rest
4,4,2,low fat,92,15 min,rest


In [133]:
df_exercise.tail(5)

,Unnamed: 0,id,diet,pulse,time,kind
85,85,29,no fat,135,15 min,running
86,86,29,no fat,130,30 min,running
87,87,30,no fat,99,1 min,running
88,88,30,no fat,111,15 min,running
89,89,30,no fat,150,30 min,running


In [134]:
df_exercise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   Unnamed: 0  90 non-null     int64   
 1   id          90 non-null     int64   
 2   diet        90 non-null     category
 3   pulse       90 non-null     int64   
 4   time        90 non-null     category
 5   kind        90 non-null     category
dtypes: category(3), int64(3)
memory usage: 2.9 KB


In [135]:
df_exercise.describe()

,Unnamed: 0,id,pulse
count,90.000000,90.000000,90.000000
mean,44.500000,15.500000,99.700000
std,26.124701,8.703932,14.858471
min,0.000000,1.000000,80.000000
25%,22.250000,8.000000,90.250000
50%,44.500000,15.500000,96.000000
75%,66.750000,23.000000,103.000000
max,89.000000,30.000000,150.000000


In [136]:
df_exercise.describe(include='all')


,Unnamed: 0,id,diet,pulse,time,kind
count,90.000000,90.000000,90,90.000000,90,90
unique,NaN,NaN,2,NaN,3,3
top,NaN,NaN,no fat,NaN,1 min,rest
freq,NaN,NaN,45,NaN,30,30
mean,44.500000,15.500000,NaN,99.700000,NaN,NaN
std,26.124701,8.703932,NaN,14.858471,NaN,NaN
min,0.000000,1.000000,NaN,80.000000,NaN,NaN
25%,22.250000,8.000000,NaN,90.250000,NaN,NaN
50%,44.500000,15.500000,NaN,96.000000,NaN,NaN
75%,66.750000,23.000000,NaN,103.000000,NaN,NaN


In [137]:
df_exercise.isnull().sum()

Unnamed: 0    0
id            0
diet          0
pulse         0
time          0
kind          0
dtype: int64

In [138]:
df_exercise['id'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [139]:
df_exercise['id'].nunique()


30

#flights dataset

A small teaching dataset of monthly airline passenger counts (classical monthly time series).
Typical shape: 144 rows (12 months × 12 years, usually 1949–1960).
Typical columns:
year (int) — year of observation.
month (object / categorical) — month name (Jan..Dec).
passengers (int) — number of passengers (count).

In [140]:
df_flights = sns.load_dataset('flights')


In [146]:
df_flights.shape

(144, 3)

In [141]:
df_flights.head(5)

,year,month,passengers
0,1949,Jan,112
1,1949,Feb,118
2,1949,Mar,132
3,1949,Apr,129
4,1949,May,121


In [142]:
df_flights.tail(5)

,year,month,passengers
139,1960,Aug,606
140,1960,Sep,508
141,1960,Oct,461
142,1960,Nov,390
143,1960,Dec,432


In [143]:
df_flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   year        144 non-null    int64   
 1   month       144 non-null    category
 2   passengers  144 non-null    int64   
dtypes: category(1), int64(2)
memory usage: 2.9 KB


In [144]:
df_flights.describe()

,year,passengers
count,144.000000,144.000000
mean,1954.500000,280.298611
std,3.464102,119.966317
min,1949.000000,104.000000
25%,1951.750000,180.000000
50%,1954.500000,265.500000
75%,1957.250000,360.500000
max,1960.000000,622.000000


In [145]:
df_flights.describe(include='all')

,year,month,passengers
count,144.000000,144,144.000000
unique,NaN,12,NaN
top,NaN,Jan,NaN
freq,NaN,12,NaN
mean,1954.500000,NaN,280.298611
std,3.464102,NaN,119.966317
min,1949.000000,NaN,104.000000
25%,1951.750000,NaN,180.000000
50%,1954.500000,NaN,265.500000
75%,1957.250000,NaN,360.500000


In [147]:
df_flights.isnull().sum()

year          0
month         0
passengers    0
dtype: int64

In [148]:
df_flights['passengers'].mean()

np.float64(280.2986111111111)

In [149]:
df_flights['passengers'].isnull().sum()

np.int64(0)

In [151]:
df_flights['passengers'].unique()

array([112, 118, 132, 129, 121, 135, 148, 136, 119, 104, 115, 126, 141,
       125, 149, 170, 158, 133, 114, 140, 145, 150, 178, 163, 172, 199,
       184, 162, 146, 166, 171, 180, 193, 181, 183, 218, 230, 242, 209,
       191, 194, 196, 236, 235, 229, 243, 264, 272, 237, 211, 201, 204,
       188, 227, 234, 302, 293, 259, 203, 233, 267, 269, 270, 315, 364,
       347, 312, 274, 278, 284, 277, 317, 313, 318, 374, 413, 405, 355,
       306, 271, 301, 356, 348, 422, 465, 467, 404, 305, 336, 340, 362,
       363, 435, 491, 505, 359, 310, 337, 360, 342, 406, 396, 420, 472,
       548, 559, 463, 407, 417, 391, 419, 461, 535, 622, 606, 508, 390,
       432])

In [152]:
df_flights['passengers'].nunique()

118

fmri dataset

A small tutorial dataset bundled with Seaborn representing a simple functional MRI experiment.
Purpose: demonstrate line/relational plots for repeated-measures time-series data (signal over time, grouped by event/region/subject).

In [156]:
df_fmri = sns.load_dataset('fmri')

In [159]:
df_fmri.shape

(1064, 5)

In [160]:
df_fmri.head(5)

,subject,timepoint,event,region,signal
0,s13,18,stim,parietal,-0.017552
1,s5,14,stim,parietal,-0.080883
2,s12,18,stim,parietal,-0.081033
3,s11,18,stim,parietal,-0.046134
4,s10,18,stim,parietal,-0.037970


In [161]:
df_fmri.tail()

,subject,timepoint,event,region,signal
1059,s0,8,cue,frontal,0.018165
1060,s13,7,cue,frontal,-0.029130
1061,s12,7,cue,frontal,-0.004939
1062,s11,7,cue,frontal,-0.025367
1063,s0,0,cue,parietal,-0.006899


In [162]:
df_fmri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1064 entries, 0 to 1063
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   subject    1064 non-null   object 
 1   timepoint  1064 non-null   int64  
 2   event      1064 non-null   object 
 3   region     1064 non-null   object 
 4   signal     1064 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 41.7+ KB


In [163]:
df_fmri.describe()

,timepoint,signal
count,1064.000000,1064.000000
mean,9.000000,0.003540
std,5.479801,0.093930
min,0.000000,-0.255486
25%,4.000000,-0.046070
50%,9.000000,-0.013653
75%,14.000000,0.024293
max,18.000000,0.564985


In [164]:
df_fmri.describe(include='all')

,subject,timepoint,event,region,signal
count,1064,1064.000000,1064,1064,1064.000000
unique,14,NaN,2,2,NaN
top,s13,NaN,stim,parietal,NaN
freq,76,NaN,532,532,NaN
mean,NaN,9.000000,NaN,NaN,0.003540
std,NaN,5.479801,NaN,NaN,0.093930
min,NaN,0.000000,NaN,NaN,-0.255486
25%,NaN,4.000000,NaN,NaN,-0.046070
50%,NaN,9.000000,NaN,NaN,-0.013653
75%,NaN,14.000000,NaN,NaN,0.024293


In [165]:
df_fmri.isnull().sum()

subject      0
timepoint    0
event        0
region       0
signal       0
dtype: int64

In [166]:
df_fmri['event'].isnull().sum()

np.int64(0)

In [167]:
df_fmri['event'].unique()

array(['stim', 'cue'], dtype=object)

In [168]:
df_fmri['event'].nunique()

2

geyser dataset

Geyser dataset notes:
- Classic small example dataset describing eruptions of the Old Faithful geyser.
- Typical columns: 'waiting' (time between eruptions) and 'duration' or 'eruptions' (length of eruption). Column names can vary by Seaborn version, so inspect first.
- Useful plots: scatter (waiting vs duration), histogram of waiting times, and simple summary stats.
- Conversion tip: convert numeric-like columns with pandas' to_numeric(errors='coerce') and prefer nullable integer types or fill NaNs before forcing .astype(int).

In [169]:
df_geyser=sns.load_dataset('geyser')

In [170]:
df_geyser.shape

(272, 3)

In [171]:
df_geyser.head(5)

,duration,waiting,kind
0,3.600,79,long
1,1.800,54,short
2,3.333,74,long
3,2.283,62,short
4,4.533,85,long


In [172]:
df_geyser.tail(5)

,duration,waiting,kind
267,4.117,81,long
268,2.150,46,short
269,4.417,90,long
270,1.817,46,short
271,4.467,74,long


In [173]:
df_geyser.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   duration  272 non-null    float64
 1   waiting   272 non-null    int64  
 2   kind      272 non-null    object 
dtypes: float64(1), int64(1), object(1)
memory usage: 6.5+ KB


In [174]:
df_geyser.describe()

,duration,waiting
count,272.000000,272.000000
mean,3.487783,70.897059
std,1.141371,13.594974
min,1.600000,43.000000
25%,2.162750,58.000000
50%,4.000000,76.000000
75%,4.454250,82.000000
max,5.100000,96.000000


In [175]:
df_geyser.describe(include='all')

,duration,waiting,kind
count,272.000000,272.000000,272
unique,NaN,NaN,2
top,NaN,NaN,long
freq,NaN,NaN,172
mean,3.487783,70.897059,NaN
std,1.141371,13.594974,NaN
min,1.600000,43.000000,NaN
25%,2.162750,58.000000,NaN
50%,4.000000,76.000000,NaN
75%,4.454250,82.000000,NaN


In [176]:
df_geyser.isnull().sum()

duration    0
waiting     0
kind        0
dtype: int64

In [177]:
df_geyser['duration'].isnull().sum()


np.int64(0)

In [ ]:
df_geyser['duration'].unique()

array([3.6  , 1.8  , 3.333, 2.283, 4.533, 2.883, 4.7  , 1.95 , 4.35 ,
       1.833, 3.917, 4.2  , 1.75 , 2.167, 4.8  , 1.6  , 4.25 , 3.45 ,
       3.067, 1.967, 4.083, 3.85 , 4.433, 4.3  , 4.467, 3.367, 4.033,
       3.833, 2.017, 1.867, 4.833, 4.783, 1.883, 4.567, 3.317, 2.1  ,
       4.633, 2.   , 4.716, 1.733, 4.883, 3.717, 1.667, 4.317, 2.233,
       4.5  , 1.817, 4.4  , 4.167, 2.067, 4.   , 1.983, 5.067, 3.883,
       4.133, 4.333, 4.1  , 2.633, 4.067, 4.933, 3.95 , 4.517, 2.2  ,
       4.817, 4.667, 3.75 , 4.9  , 2.483, 4.367, 4.05 , 1.783, 4.85 ,
       3.683, 4.733, 2.3  , 4.417, 1.7  , 2.317, 4.6  , 2.617, 3.767,
       1.917, 2.267, 4.65 , 2.8  , 4.383, 2.033, 3.733, 4.233, 5.1  ,
       5.033, 2.4  , 3.567, 3.967, 4.15 , 3.5  , 4.583, 2.367, 5.   ,
       1.933, 4.617, 2.083, 2.417, 2.183, 3.966, 4.366, 2.25 , 2.383,
       3.417, 4.267, 4.483, 4.117, 4.55 , 4.183, 2.217, 4.45 , 1.85 ,
       4.283, 2.333, 2.35 , 2.9  , 2.133, 3.817, 4.767, 4.75 , 2.15 ])

In [179]:
df_geyser['duration'].nunique()

126

glue dataset

glue is a tiny example/toy dataset bundled with Seaborn for teaching and plotting. Its exact columns can vary between Seaborn releases, so always inspect before assuming schema.
Typically it contains a mix of a few numeric and categorical columns suitable for boxplots, small group comparisons, or pairwise plots

In [180]:
df_glue = sns.load_dataset('glue')

In [181]:
df_glue.shape

(64, 5)

In [182]:
df_glue.head(5)

,Model,Year,Encoder,Task,Score
0,ERNIE,2019,Transformer,CoLA,75.5
1,T5,2019,Transformer,CoLA,71.6
2,RoBERTa,2019,Transformer,CoLA,67.8
3,BERT,2018,Transformer,CoLA,60.5
4,BiLSTM+ELMo,2018,LSTM,CoLA,32.1


In [183]:
df_glue.tail(5)

,Model,Year,Encoder,Task,Score
59,BERT,2018,Transformer,RTE,70.1
60,BiLSTM+ELMo,2018,LSTM,RTE,57.4
61,BiLSTM+CoVe,2017,LSTM,RTE,52.7
62,BiLSTM+Attn,2017,LSTM,RTE,58.4
63,BiLSTM,2017,LSTM,RTE,57.4


In [184]:
df_glue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Model    64 non-null     object 
 1   Year     64 non-null     int64  
 2   Encoder  64 non-null     object 
 3   Task     64 non-null     object 
 4   Score    64 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 2.6+ KB


In [185]:
df_glue.describe()

,Year,Score
count,64.000000,64.000000
mean,2018.000000,75.579688
std,0.872872,19.289698
min,2017.000000,11.600000
25%,2017.000000,66.800000
50%,2018.000000,75.500000
75%,2019.000000,92.225000
max,2019.000000,97.800000


In [186]:
df_glue.describe(include='all')

,Model,Year,Encoder,Task,Score
count,64,64.000000,64,64,64.000000
unique,8,NaN,2,8,NaN
top,ERNIE,NaN,Transformer,CoLA,NaN
freq,8,NaN,32,8,NaN
mean,NaN,2018.000000,NaN,NaN,75.579688
std,NaN,0.872872,NaN,NaN,19.289698
min,NaN,2017.000000,NaN,NaN,11.600000
25%,NaN,2017.000000,NaN,NaN,66.800000
50%,NaN,2018.000000,NaN,NaN,75.500000
75%,NaN,2019.000000,NaN,NaN,92.225000


In [187]:
df_glue.isnull().sum()

Model      0
Year       0
Encoder    0
Task       0
Score      0
dtype: int64

In [188]:
df_glue['Encoder'].isnull().sum()

np.int64(0)

In [189]:
df_glue['Model'].unique()

array(['ERNIE', 'T5', 'RoBERTa', 'BERT', 'BiLSTM+ELMo', 'BiLSTM+CoVe',
       'BiLSTM+Attn', 'BiLSTM'], dtype=object)

In [190]:
df_glue['Model'].nunique()

8

healthexp dataset

healthexp is a small example/toy dataset bundled with Seaborn for teaching plotting and simple analysis of health-related measures. Exact columns vary by Seaborn release, so inspect first — common uses are visualizing relationships between health expenditure and outcomes (e.g., life expectancy), and comparing groups (region, country, year).

In [191]:
df_healthexp = sns.load_dataset("healthexp")

In [192]:
df_healthexp.shape

(274, 4)

In [193]:
df_healthexp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Year             274 non-null    int64  
 1   Country          274 non-null    object 
 2   Spending_USD     274 non-null    float64
 3   Life_Expectancy  274 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 8.7+ KB


In [194]:
df_healthexp.head(5)

,Year,Country,Spending_USD,Life_Expectancy
0,1970,Germany,252.311,70.6
1,1970,France,192.143,72.2
2,1970,Great Britain,123.993,71.9
3,1970,Japan,150.437,72.0
4,1970,USA,326.961,70.9


In [195]:
df_healthexp.tail(5)

,Year,Country,Spending_USD,Life_Expectancy
269,2020,Germany,6938.983,81.1
270,2020,France,5468.418,82.3
271,2020,Great Britain,5018.700,80.4
272,2020,Japan,4665.641,84.7
273,2020,USA,11859.179,77.0


In [196]:
df_healthexp.describe()

,Year,Spending_USD,Life_Expectancy
count,274.000000,274.000000,274.000000
mean,1996.992701,2789.338905,77.909489
std,14.180933,2194.939785,3.276263
min,1970.000000,123.993000,70.600000
25%,1985.250000,1038.357000,75.525000
50%,1998.000000,2295.578000,78.100000
75%,2009.000000,4055.610000,80.575000
max,2020.000000,11859.179000,84.700000


In [197]:
df_healthexp.describe(include='all')

,Year,Country,Spending_USD,Life_Expectancy
count,274.000000,274,274.000000,274.000000
unique,NaN,6,NaN,NaN
top,NaN,Japan,NaN,NaN
freq,NaN,51,NaN,NaN
mean,1996.992701,NaN,2789.338905,77.909489
std,14.180933,NaN,2194.939785,3.276263
min,1970.000000,NaN,123.993000,70.600000
25%,1985.250000,NaN,1038.357000,75.525000
50%,1998.000000,NaN,2295.578000,78.100000
75%,2009.000000,NaN,4055.610000,80.575000


In [198]:
df_healthexp.isnull().sum()

Year               0
Country            0
Spending_USD       0
Life_Expectancy    0
dtype: int64

In [199]:
df_healthexp['Country'].isnull().sum()

np.int64(0)

In [200]:
df_healthexp['Country'].unique()

array(['Germany', 'France', 'Great Britain', 'Japan', 'USA', 'Canada'],
      dtype=object)

In [201]:
df_healthexp['Country'].nunique()

6

iris dataset

Classic small teaching dataset for multivariate classification and visualization.
Typical columns: sepal_length, sepal_width, petal_length, petal_width (numeric), and species (categorical with values like "setosa", "versicolor", "virginica").
Useful for pairwise plots, classification demos, cluster/PCA examples, and simple summary stats.

In [202]:
df_iris = sns.load_dataset("iris")


In [203]:
df_iris.shape

(150, 5)

In [204]:
df_iris.head(5)

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [205]:
df_iris.tail(5)

,sepal_length,sepal_width,petal_length,petal_width,species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica


In [206]:
df_iris.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [207]:
df_iris.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [208]:
df_iris.describe(include='all')

,sepal_length,sepal_width,petal_length,petal_width,species
count,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,setosa
freq,NaN,NaN,NaN,NaN,50
mean,5.843333,3.057333,3.758000,1.199333,NaN
std,0.828066,0.435866,1.765298,0.762238,NaN
min,4.300000,2.000000,1.000000,0.100000,NaN
25%,5.100000,2.800000,1.600000,0.300000,NaN
50%,5.800000,3.000000,4.350000,1.300000,NaN
75%,6.400000,3.300000,5.100000,1.800000,NaN


In [209]:
df_iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [210]:
df_iris['species'].isnull().sum()

np.int64(0)

In [211]:
df_iris['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [212]:
df_iris['species'].nunique()

3

mpg dataset

Classic automotive fuel-efficiency dataset (from the UCI Auto MPG data) included in Seaborn.
Typical columns: mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin, name.
Common issues: horsepower can contain non-numeric values or missing entries in some releases — coerce safely before numeric ops.

In [213]:
df_mpg = sns.load_dataset('mpg')

In [214]:
df_mpg.shape

(398, 9)

In [215]:
df_mpg.head(5)


,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino


In [216]:
df_mpg.tail(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10


In [217]:
df_mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [218]:
df_mpg.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000


In [219]:
df_mpg.describe(include='all')


,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usa,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,NaN,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,NaN,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,NaN,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,NaN,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,NaN,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,NaN,NaN


In [220]:
df_mpg.isnull().sum()


mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [221]:
df_mpg['cylinders'].isnull().sum()
    

np.int64(0)

In [223]:
df_mpg['cylinders'].unique()

array([8, 4, 6, 3, 5])

In [224]:
df_mpg['cylinders'].nunique()

5

penguins dataset

Small, well-known teaching dataset of penguin measurements from the Palmer Archipelago.
Typical columns: species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year.
Common issues: a few missing values (often in sex and some numeric measurements) — inspect before casting.


In [225]:
df_penguins = sns.load_dataset('penguins')

In [226]:
df_penguins.shape

(344, 7)

In [227]:
df_penguins.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female


In [228]:
df_penguins.tail(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male


In [229]:
df_penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [230]:
df_penguins.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
count,342.000000,342.000000,342.000000,342.000000
mean,43.921930,17.151170,200.915205,4201.754386
std,5.459584,1.974793,14.061714,801.954536
min,32.100000,13.100000,172.000000,2700.000000
25%,39.225000,15.600000,190.000000,3550.000000
50%,44.450000,17.300000,197.000000,4050.000000
75%,48.500000,18.700000,213.000000,4750.000000
max,59.600000,21.500000,231.000000,6300.000000


In [231]:
df_penguins.describe(include='all')

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
count,344,344,342.000000,342.000000,342.000000,342.000000,333
unique,3,3,NaN,NaN,NaN,NaN,2
top,Adelie,Biscoe,NaN,NaN,NaN,NaN,Male
freq,152,168,NaN,NaN,NaN,NaN,168
mean,NaN,NaN,43.921930,17.151170,200.915205,4201.754386,NaN
std,NaN,NaN,5.459584,1.974793,14.061714,801.954536,NaN
min,NaN,NaN,32.100000,13.100000,172.000000,2700.000000,NaN
25%,NaN,NaN,39.225000,15.600000,190.000000,3550.000000,NaN
50%,NaN,NaN,44.450000,17.300000,197.000000,4050.000000,NaN
75%,NaN,NaN,48.500000,18.700000,213.000000,4750.000000,NaN


In [232]:
df_penguins.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [233]:
df_penguins['species'].isnull().sum()   

np.int64(0)

In [234]:
df_penguins['species'].unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [235]:
df_penguins['species'].nunique()

3

planets dataset


Each row represents an exoplanet discovery (teaching/example dataset).
Typical columns: method (discovery method, categorical), number (integer count related to system), orbital_period (float, days), mass (float, Jupiter masses), distance (float, parsecs or light-years depending on version).
Use-cases: categorical comparisons by discovery method, distributions of orbital period/mass, scatter/relationship (often highly skewed → use log scale).

In [236]:
df_planets = sns.load_dataset('planets')

In [237]:
df_planets.shape

(1035, 6)

In [238]:
df_planets.head(5)

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300,7.10,77.40,2006
1,Radial Velocity,1,874.774,2.21,56.95,2008
2,Radial Velocity,1,763.000,2.60,19.84,2011
3,Radial Velocity,1,326.030,19.40,110.62,2007
4,Radial Velocity,1,516.220,10.50,119.47,2009


In [239]:
df_planets.tail(5)

,method,number,orbital_period,mass,distance,year
1030,Transit,1,3.941507,NaN,172.0,2006
1031,Transit,1,2.615864,NaN,148.0,2007
1032,Transit,1,3.191524,NaN,174.0,2007
1033,Transit,1,4.125083,NaN,293.0,2008
1034,Transit,1,4.187757,NaN,260.0,2008


In [240]:
df_planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [241]:
df_planets.describe()

,number,orbital_period,mass,distance,year
count,1035.000000,992.000000,513.000000,808.000000,1035.000000
mean,1.785507,2002.917596,2.638161,264.069282,2009.070531
std,1.240976,26014.728304,3.818617,733.116493,3.972567
min,1.000000,0.090706,0.003600,1.350000,1989.000000
25%,1.000000,5.442540,0.229000,32.560000,2007.000000
50%,1.000000,39.979500,1.260000,55.250000,2010.000000
75%,2.000000,526.005000,3.040000,178.500000,2012.000000
max,7.000000,730000.000000,25.000000,8500.000000,2014.000000


In [242]:
df_planets.describe(include='all')

,method,number,orbital_period,mass,distance,year
count,1035,1035.000000,992.000000,513.000000,808.000000,1035.000000
unique,10,NaN,NaN,NaN,NaN,NaN
top,Radial Velocity,NaN,NaN,NaN,NaN,NaN
freq,553,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.785507,2002.917596,2.638161,264.069282,2009.070531
std,NaN,1.240976,26014.728304,3.818617,733.116493,3.972567
min,NaN,1.000000,0.090706,0.003600,1.350000,1989.000000
25%,NaN,1.000000,5.442540,0.229000,32.560000,2007.000000
50%,NaN,1.000000,39.979500,1.260000,55.250000,2010.000000
75%,NaN,2.000000,526.005000,3.040000,178.500000,2012.000000


In [243]:
df_planets['mass'].isnull().sum()

np.int64(522)

In [244]:
df_planets.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [245]:
df_planets['mass'].mean()

np.float64(2.6381605847953216)

In [246]:
df_planets['mass'].unique()

array([7.1000e+00, 2.2100e+00, 2.6000e+00, 1.9400e+01, 1.0500e+01,
       4.8000e+00, 4.6400e+00,        nan, 1.0300e+01, 1.9900e+00,
       8.6000e-01, 9.8800e+00, 3.8800e+00, 2.5300e+00, 5.4000e-01,
       1.6400e+00, 4.7200e-01, 8.0000e-01, 1.6500e-01, 3.5300e+00,
       1.7200e-01, 1.6000e-02, 5.7000e-02, 7.2000e-02, 5.3000e+00,
       3.2000e+00, 6.0500e+00, 4.2000e+00, 1.8000e+00, 3.6000e-03,
       1.5500e+00, 7.6000e+00, 8.7800e+00, 1.8500e+00, 2.8000e+00,
       1.7000e+00, 1.0400e+00, 3.9000e+00, 2.0600e+01, 6.8760e-01,
       1.9810e+00, 4.1320e+00, 1.0590e+00, 5.1000e+00, 1.0600e+01,
       4.5000e-02, 3.3000e-01, 2.7000e-02, 1.7000e-01, 1.4700e+00,
       1.1100e+00, 2.1420e+01, 1.2470e+01, 9.1000e-01, 3.9100e+00,
       3.5000e-02, 2.4000e-02, 7.9000e-02, 8.2000e-01, 1.8940e+00,
       1.6000e+00, 2.3000e+00, 1.8000e-02, 4.9000e-02, 1.7000e-02,
       2.2000e-02, 6.0000e-03, 3.2800e-01, 1.2000e-02, 8.0000e-03,
       1.4000e-02, 4.9500e+00, 3.6000e-02, 6.4000e-01, 2.2756e

In [247]:
df_planets['mass'].nunique()

381

seaice dataset

Teach and demonstrate time-series and seasonal analysis (visualization and aggregation).
Compare seasonal cycles between hemispheres.
Compute long-term trends and anomalies (e.g., detrended seasonal cycle, rolling averages).
Example analyses: monthly climatology, annual means, seasonal boxp

In [248]:
df_seaice = sns.load_dataset('seaice')

In [249]:
df_seaice.shape

(13175, 2)

In [250]:
df_seaice.head(5)

,Date,Extent
0,1980-01-01,14.200
1,1980-01-03,14.302
2,1980-01-05,14.414
3,1980-01-07,14.518
4,1980-01-09,14.594


In [251]:
df_seaice.tail(5)

,Date,Extent
13170,2019-12-27,12.721
13171,2019-12-28,12.712
13172,2019-12-29,12.780
13173,2019-12-30,12.858
13174,2019-12-31,12.889


In [252]:
df_seaice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13175 entries, 0 to 13174
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    13175 non-null  datetime64[ns]
 1   Extent  13175 non-null  float64       
dtypes: datetime64[ns](1), float64(1)
memory usage: 206.0 KB


In [253]:
df_seaice.describe()

,Date,Extent
count,13175,13175.000000
mean,2001-09-30 12:50:39.574952448,11.289508
min,1980-01-01 00:00:00,3.340000
25%,1992-12-11 12:00:00,8.551500
50%,2001-12-18 00:00:00,11.982000
75%,2010-12-24 12:00:00,14.204500
max,2019-12-31 00:00:00,16.412000
std,NaN,3.284901


In [254]:
df_seaice.describe(include='all')


,Date,Extent
count,13175,13175.000000
mean,2001-09-30 12:50:39.574952448,11.289508
min,1980-01-01 00:00:00,3.340000
25%,1992-12-11 12:00:00,8.551500
50%,2001-12-18 00:00:00,11.982000
75%,2010-12-24 12:00:00,14.204500
max,2019-12-31 00:00:00,16.412000
std,NaN,3.284901


In [255]:
df_seaice.isnull().sum()

Date      0
Extent    0
dtype: int64

In [256]:
df_seaice['Date'].isnull().sum()

np.int64(0)

In [257]:
df_seaice['Date'].unique()

<DatetimeArray>
['1980-01-01 00:00:00', '1980-01-03 00:00:00', '1980-01-05 00:00:00',
 '1980-01-07 00:00:00', '1980-01-09 00:00:00', '1980-01-11 00:00:00',
 '1980-01-13 00:00:00', '1980-01-15 00:00:00', '1980-01-17 00:00:00',
 '1980-01-19 00:00:00',
 ...
 '2019-12-22 00:00:00', '2019-12-23 00:00:00', '2019-12-24 00:00:00',
 '2019-12-25 00:00:00', '2019-12-26 00:00:00', '2019-12-27 00:00:00',
 '2019-12-28 00:00:00', '2019-12-29 00:00:00', '2019-12-30 00:00:00',
 '2019-12-31 00:00:00']
Length: 13175, dtype: datetime64[ns]

In [258]:
df_seaice['Date'].nunique()

13175

taxis dataset

Teach time-of-day / day-of-week patterns (trips per hour, rush vs night).
Tip / fare analysis (tip percentage, tip ~ fare relationships).
Distribution analysis (fares and distances are heavily skewed; log scale or clipping helps).
Outlier detection and cleaning practice (very large fares or zero fares).

In [259]:
df_taxis = sns.load_dataset('taxis')

In [260]:
df_taxis.shape

(6433, 14)

In [261]:
df_taxis.head(5)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan


In [262]:
df_taxis.tail(5)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn


In [263]:
df_taxis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64         
 3   distance         6433 non-null   float64       
 4   fare             6433 non-null   float64       
 5   tip              6433 non-null   float64       
 6   tolls            6433 non-null   float64       
 7   total            6433 non-null   float64       
 8   color            6433 non-null   object        
 9   payment          6389 non-null   object        
 10  pickup_zone      6407 non-null   object        
 11  dropoff_zone     6388 non-null   object        
 12  pickup_borough   6407 non-null   object        
 13  dropoff_borough  6388 non-null   object        
dtypes: datetime64[ns](2), float64(5), int64(

In [264]:
df_taxis.describe()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total
count,6433,6433,6433.000000,6433.000000,6433.000000,6433.00000,6433.000000,6433.000000
mean,2019-03-16 08:31:28.514223616,2019-03-16 08:45:49.491217408,1.539251,3.024617,13.091073,1.97922,0.325273,18.517794
min,2019-02-28 23:29:03,2019-02-28 23:32:35,0.000000,0.000000,1.000000,0.00000,0.000000,1.300000
25%,2019-03-08 15:50:34,2019-03-08 16:12:51,1.000000,0.980000,6.500000,0.00000,0.000000,10.800000
50%,2019-03-15 21:46:58,2019-03-15 22:06:44,1.000000,1.640000,9.500000,1.70000,0.000000,14.160000
75%,2019-03-23 17:41:38,2019-03-23 17:51:56,2.000000,3.210000,15.000000,2.80000,0.000000,20.300000
max,2019-03-31 23:43:45,2019-04-01 00:13:58,6.000000,36.700000,150.000000,33.20000,24.020000,174.820000
std,NaN,NaN,1.203768,3.827867,11.551804,2.44856,1.415267,13.815570


In [265]:
df_taxis.describe(include='all')

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
count,6433,6433,6433.000000,6433.000000,6433.000000,6433.00000,6433.000000,6433.000000,6433,6389,6407,6388,6407,6388
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,194,203,4,5
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yellow,credit card,Midtown Center,Upper East Side North,Manhattan,Manhattan
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5451,4577,230,245,5268,5206
mean,2019-03-16 08:31:28.514223616,2019-03-16 08:45:49.491217408,1.539251,3.024617,13.091073,1.97922,0.325273,18.517794,NaN,NaN,NaN,NaN,NaN,NaN
min,2019-02-28 23:29:03,2019-02-28 23:32:35,0.000000,0.000000,1.000000,0.00000,0.000000,1.300000,NaN,NaN,NaN,NaN,NaN,NaN
25%,2019-03-08 15:50:34,2019-03-08 16:12:51,1.000000,0.980000,6.500000,0.00000,0.000000,10.800000,NaN,NaN,NaN,NaN,NaN,NaN
50%,2019-03-15 21:46:58,2019-03-15 22:06:44,1.000000,1.640000,9.500000,1.70000,0.000000,14.160000,NaN,NaN,NaN,NaN,NaN,NaN
75%,2019-03-23 17:41:38,2019-03-23 17:51:56,2.000000,3.210000,15.000000,2.80000,0.000000,20.300000,NaN,NaN,NaN,NaN,NaN,NaN
max,2019-03-31 23:43:45,2019-04-01 00:13:58,6.000000,36.700000,150.000000,33.20000,24.020000,174.820000,NaN,NaN,NaN,NaN,NaN,NaN


In [266]:
df_taxis.isnull().sum() 

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [268]:
df_taxis['total'].isnull().sum()

np.int64(0)

In [269]:
df_taxis['total'].unique()

array([ 12.95,   9.3 ,  14.16,  36.95,  13.4 ,  12.96,  18.8 ,  11.8 ,
        19.3 ,  13.3 ,  17.8 ,  11.3 ,  13.8 ,  14.8 ,  16.8 ,  16.3 ,
        14.72,  11.38,  11.84,  11.6 ,  49.87,  16.64,  17.3 ,  19.56,
        18.3 ,  15.3 ,  12.36,   7.8 ,   9.8 ,  10.79,  25.56,  24.8 ,
        16.56,  36.36,  23.3 , 100.38,  35.06,  33.8 ,  18.95,  11.44,
        21.3 ,  37.8 ,  17.15,  26.76,  65.56,  10.56,  12.3 ,   6.3 ,
        20.8 ,  15.38,  22.56,  12.09,  21.8 ,  17.76,  11.75,   9.95,
        14.6 ,  13.55,   7.3 ,  15.96,  12.8 ,  10.38,  19.8 ,   3.8 ,
        29.75,   7.25,  40.06,  14.  ,  19.2 ,  15.35,  20.16,  39.06,
        17.16,  11.27,  27.95,  58.27,  16.55,  27.88,  11.16,  22.55,
         8.58,  10.8 ,   4.3 ,  18.35,  12.42,  13.5 ,  38.41,  57.56,
        21.96,  12.74,  14.3 ,   9.36,  21.95,  31.56,  23.16,  20.47,
        13.56,  18.5 ,   8.3 ,  44.76,  14.75,   8.76,  15.8 ,  38.62,
         8.8 ,   9.75,  78.66,  10.3 ,  11.62,  16.62,  29.8 ,   8.91,
      

In [270]:
df_taxis['total'].nunique()

898

tips dataset


Teach relational plots, categorical comparisons, and simple regression.
Common tasks: tip rate analysis (tip% = tip/total_bill), compare tip behavior by day/time/smoker, model tip vs bill (regression), and visualize distributions (box/violin/hist).

In [271]:
df_tips = sns.load_dataset('tips')

In [272]:
df_tips.shape

(244, 7)

In [273]:
df_tips.head(5)

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [274]:
df_tips.tail(5)

,total_bill,tip,sex,smoker,day,time,size
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2
243,18.78,3.00,Female,No,Thur,Dinner,2


In [275]:
df_tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [276]:
df_tips.describe()

,total_bill,tip,size
count,244.000000,244.000000,244.000000
mean,19.785943,2.998279,2.569672
std,8.902412,1.383638,0.951100
min,3.070000,1.000000,1.000000
25%,13.347500,2.000000,2.000000
50%,17.795000,2.900000,2.000000
75%,24.127500,3.562500,3.000000
max,50.810000,10.000000,6.000000


In [277]:
df_tips.describe(include='all')

,total_bill,tip,sex,smoker,day,time,size
count,244.000000,244.000000,244,244,244,244,244.000000
unique,NaN,NaN,2,2,4,2,NaN
top,NaN,NaN,Male,No,Sat,Dinner,NaN
freq,NaN,NaN,157,151,87,176,NaN
mean,19.785943,2.998279,NaN,NaN,NaN,NaN,2.569672
std,8.902412,1.383638,NaN,NaN,NaN,NaN,0.951100
min,3.070000,1.000000,NaN,NaN,NaN,NaN,1.000000
25%,13.347500,2.000000,NaN,NaN,NaN,NaN,2.000000
50%,17.795000,2.900000,NaN,NaN,NaN,NaN,2.000000
75%,24.127500,3.562500,NaN,NaN,NaN,NaN,3.000000


In [278]:
df_tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [279]:
df_tips['size'].isnull().sum()

np.int64(0)

In [281]:
df_tips['size'].unique()

array([2, 3, 4, 1, 6, 5])

In [282]:
df_tips['size'].nunique()

6

titanic dataset


A small teaching dataset where each row is a passenger on the Titanic.
Key columns you’ll typically see: survived (target 0/1), pclass (1/2/3), sex, age, sibsp, parch, fare, embarked/embarked_town, plus derived fields like class, who, deck, alive, alone.
Size: a few hundred rows — ideal for examples, EDA, and simple classification demos.

In [283]:
df_titanic = sns.load_dataset('titanic')

In [285]:
df_titanic.shape

(891, 15)

In [286]:
df_titanic.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [287]:
df_titanic.tail(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True


In [288]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [289]:
df_titanic.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [290]:
df_titanic.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [291]:
df_titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [292]:
df_titanic['age'].isnull().sum()

np.int64(177)

In [293]:
df_titanic['age'].mean()

np.float64(29.69911764705882)

In [294]:
df_titanic['age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [295]:
df_titanic['age'].nunique()

88